[build]
  publish = "public"
  command = "# no build command"

# Pengaturan untuk rute-rute SPA (Single Page Application)
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/claim"
  to = "/claim.html"
  status = 200

# Fallback untuk API routes - ini akan mengembalikan 404
# karena Netlify tidak bisa menjalankan server Express
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
